# Profile information
name: tkvtv
title: tkvtv - 取引量No.1！ *当社比
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/page110" # the subpath of your site, e.g. /blog
url: "https://takagotch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: takagotch
twitter: #Add your Twitter
google-plus: #Add your Google+
github: takagotch

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
